name: Deploy Storefront

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs

      - name: Deploy
        uses: actions/deploy-pages@v2
