name: Route GitHub Notification to OracleSignal

on:
  push:
    branches: [ main ]
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, merged]
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send Notification to OracleSignal
      run: |
        curl -X POST https://oraclesignal.site/api/trigger \
        -H "Content-Type: application/json" \
        -d '{
          "source": "github",
          "contributor_id": "raging-asian-911",
          "emotion_tag": "signal",
          "action": "push",
          "timestamp": "'$(date -Iseconds)'",
          "payout_target": "coinbase",
          "index_url": "https://oraclesignal.site/vaults/github-drop"
        }'
