name: Talent Console Intake

on:
  workflow_dispatch:
    inputs:
      stage_name:
        description: "Contributor alias or stage name"
        required: true
      role:
        description: "Role (Performer, Director, Editor, Affiliate)"
        required: true
      portfolio:
        description: "Portfolio or social link"
        required: true
      emotional_tag:
        description: "Emotional tag (🔥, 💎, 🧿, 📜)"
        required: true
      consent:
        description: "Consent to archive (true/false)"
        required: true

jobs:
  intake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log Contributor Intake
        run: |
          mkdir -p logs/talent
          echo "{ \
            \"name\": \"${{ github.event.inputs.stage_name }}\", \
            \"role\": \"${{ github.event.inputs.role }}\", \
            \"portfolio\": \"${{ github.event.inputs.portfolio }}\", \
            \"tag\": \"${{ github.event.inputs.emotional_tag }}\", \
            \"consent\": \"${{ github.event.inputs.consent }}\", \
            \"joined\": \"$(date)\" \
          }" > logs/talent/${{ github.actor }}.json

      - name: Push to Secure Branch
        run: |
          git config --global user.name "TempleBot"
          git config --global user.email "templebot@users.noreply.github.com"
          git checkout -b talent-logs
          git add logs/talent/${{ github.actor }}.json
          git commit -m "Add talent intake for ${{ github.actor }}"
          git push origin talent-logs --force
